# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BarcodeScanner(object):
    def setupUi(self, BarcodeScanner):
        BarcodeScanner.setObjectName("BarcodeScanner")
        BarcodeScanner.resize(940, 760)
        self.centralwidget = QtWidgets.QWidget(BarcodeScanner)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Screen = QtWidgets.QLabel(self.widget)
        self.Screen.setScaledContents(False)
        self.Screen.setIndent(-1)
        self.Screen.setObjectName("Screen")
        self.verticalLayout.addWidget(self.Screen)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        self.SaveButton = QtWidgets.QRadioButton(self.tab_5)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 1, 1, 1, 1)
        self.ScanButton = QtWidgets.QPushButton(self.tab_5)
        self.ScanButton.setObjectName("ScanButton")
        self.gridLayout.addWidget(self.ScanButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SearchButton = QtWidgets.QPushButton(self.tab_6)
        self.SearchButton.setObjectName("SearchButton")
        self.gridLayout_2.addWidget(self.SearchButton, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.ClearButton = QtWidgets.QPushButton(self.tab_6)
        self.ClearButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.ClearButton, 1, 1, 1, 1)
        self.HistoryList = QtWidgets.QTreeWidget(self.tab_6)
        self.HistoryList.setObjectName("HistoryList")
        self.gridLayout_2.addWidget(self.HistoryList, 0, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        BarcodeScanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BarcodeScanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        BarcodeScanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BarcodeScanner)
        self.statusbar.setObjectName("statusbar")
        BarcodeScanner.setStatusBar(self.statusbar)

        self.retranslateUi(BarcodeScanner)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BarcodeScanner)

    def retranslateUi(self, BarcodeScanner):
        _translate = QtCore.QCoreApplication.translate
        BarcodeScanner.setWindowTitle(_translate("BarcodeScanner", "Barcode Scanner"))
        self.Screen.setText(_translate("BarcodeScanner", "TextLabel"))
        self.SaveButton.setText(_translate("BarcodeScanner", "Сохранять в истории"))
        self.ScanButton.setText(_translate("BarcodeScanner", "Сканировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("BarcodeScanner", "Сканер"))
        self.SearchButton.setText(_translate("BarcodeScanner", "Искать в сети"))
        self.ClearButton.setText(_translate("BarcodeScanner", "Очистить историю"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("BarcodeScanner", "История"))
